wandb_version: 1

seed:
  desc: null
  value: 222
dataset_name:
  desc: null
  value: scierc_sup
model_name_or_path:
  desc: null
  value: .//seq0/640000samples/lora_init/ai_unsup_roberta/
output_dir:
  desc: null
  value: .//seq0/640000samples/lora_init/ai_unsup_roberta/
lr:
  desc: null
  value: 3.0e-05
batch_size:
  desc: null
  value: 16
params:
  desc: null
  value: null
epoch:
  desc: null
  value: 30
least_epoch:
  desc: null
  value: null
patient:
  desc: null
  value: 3
weight_decay:
  desc: null
  value: 0.01
tensorboard_dir:
  desc: null
  value: null
class_num:
  desc: null
  value: null
log_dir:
  desc: null
  value: null
precision:
  desc: null
  value: torch.float32
problem_type:
  desc: null
  value: single_label_classification
round:
  desc: null
  value: null
baseline:
  desc: null
  value: lora_init
saved_model:
  desc: null
  value: null
saved_output_dir:
  desc: null
  value: ./ckpt
finetune_type:
  desc: null
  value: lora_piggyback
max_seq_length:
  desc: null
  value: 164
generator:
  desc: null
  value: ''
train_sample_ratio:
  desc: null
  value: null
n_tokens:
  desc: null
  value: 100
num_warmup_steps:
  desc: null
  value: 0
lr_scheduler_type:
  desc: null
  value: linear
gradient_accumulation_steps:
  desc: null
  value: 1
max_train_steps:
  desc: null
  value: null
how_to_block:
  desc: null
  value: null
addition_loss:
  desc: null
  value: ''
mlm_probability:
  desc: null
  value: 0.15
idrandom:
  desc: null
  value: 0
pt_task:
  desc: null
  value: 2
ft_task:
  desc: null
  value: 2
ntasks:
  desc: null
  value: 6
max_samples:
  desc: null
  value: 640000
base_dir:
  desc: null
  value: ./
no_cuda:
  desc: null
  value: false
s:
  desc: null
  value: 400
smax:
  desc: null
  value: 400
beta:
  desc: null
  value: 0.03
gamma:
  desc: null
  value: 0.75
alpha:
  desc: null
  value: 0.01
semantic_cap_size:
  desc: null
  value: 3
num_semantic_cap:
  desc: null
  value: 3
pipline_norm:
  desc: null
  value: standard_norm
hyperparameter_tune:
  desc: null
  value: false
eval_only:
  desc: null
  value: false
sequence_file:
  desc: null
  value: posttrain
reduction_factor:
  desc: null
  value: 16
lora_r:
  desc: null
  value: 8
lora_alpha:
  desc: null
  value: 16
base_model_name_or_path:
  desc: null
  value: roberta-base
task:
  desc: null
  value: 2
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720082780
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.7.13
      5: 0.17.0
      6: 4.17.0
      8:
      - 5
      10:
      - 3
      13: linux-x86_64
