wandb_version: 1

baseline:
  value: lora_init
epoch:
  value: 17
finetune_type:
  value: lora_piggyback
ft_task:
  value: 0
hyperparameter_tune:
  value: true
idrandom:
  value: 0
lr:
  value: 7.343082687700502e-05
max_samples:
  value: 640000
max_seq_length:
  value: 164
ntasks:
  value: 1
pt_task:
  value: 0
seed:
  value: 1
weight_decay:
  value: 0.0010056043660498994
